### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by drjoemanlove**
Consider the following change?

### CODE REVIEW

**Comment by joemanlove** [comment]
For real?

**Comment by drjoemanlove** [comment]
> For real?

Yes for real.

**Comment by drjoemanlove** [comment]
I also added the 1.0 code that we wrote.

**Comment by joemanlove** [comment]
Dude, you're suffering a mental break.

**Comment by drjoemanlove** [comment]
You mean we're suffering a mental break...

**Comment by joemanlove** [comment]
Fair.

**Pull request merged**
